# === Netlify config for Kainrax forum (EN build) ===
# Рабочая директория — папка forumen в репозитории
[build]
  base = "forumen"
  publish = "."
  command = "npm run build"

  # Жёстко фиксируем Node 20 (и в UI переменную тоже не помешает)
  [build.environment]
    NODE_VERSION = "20"

# Короткие URL на тред
[[redirects]]
  from = "/t/:id"
  to = "/thread.html#/:id"
  status = 302

# Кэш индекса тредов на 1 минуту
[[headers]]
  for = "/content/threads-index.json"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"

# Можно слегка кэшировать и список авторов/комментов, если есть
[[headers]]
  for = "/content/*.json"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"

# CSP и базовые заголовки безопасности, + доступ для Метрики
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://mc.yandex.ru;
    connect-src 'self' https://mc.yandex.ru;
    img-src 'self' data: https://mc.yandex.ru;
    style-src 'self' 'unsafe-inline';
    base-uri 'self';
    frame-ancestors 'self'
  """
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

# Если когда-нибудь появятся serverless-функции — раскомментируй
# [functions]
#   node_bundler = "esbuild"
#   included_files = ["content/**"]
#   directory = "netlify/functions"
