# === Netlify config for Kainrax forum ===
[build]
  base = "forumen"
  publish = "."
  command = "npm run build"

  [build.environment]
    NODE_VERSION = "20"

# Короткие URL на тред
[[redirects]]
  from = "/t/:id"
  to = "/thread.html#/:id"
  status = 302

# Кэш индексных JSON на минуту
[[headers]]
  for = "/content/*.json"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"

# CSP и базовые заголовки
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://mc.yandex.ru;
    connect-src 'self' https://mc.yandex.ru;
    img-src 'self' data: https://mc.yandex.ru;
    style-src 'self' 'unsafe-inline';
    base-uri 'self';
    frame-ancestors 'self'
  """
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
