[build]
  base = "forum"
  publish = "."
  command = "node scripts/build-index.mjs"

[build.environment]
  NODE_VERSION = "20"

# короткие URL на тред
[[redirects]]
  from = "/t/:id"
  to = "/thread.html#/:id"
  status = 302

# кэш индекса на минуту
[[headers]]
  for = "/content/threads-index.json"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"
