backend:
  name: git-gateway
  branch: main
media_folder: "forum/assets"
public_folder: "/assets"

collections:
  - name: "threads"
    label: "Темы"
    folder: "forum/content/threads"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Автор", name: "author", widget: "string"}
      - {label: "Сектор", name: "sector", widget: "string", required: false}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Создано", name: "created", widget: "datetime"}
      - {label: "Статус", name: "status", widget: "select", options: ["open","locked"], default: "open"}
      - {label: "Текст", name: "body", widget: "text"}
  - name: "index"
    label: "Индекс"
    files:
      - label: "Список тем"
        name: "threads-index"
        file: "forum/content/threads-index.json"
        fields:
          - {label: "Темы", name: "root", widget: "list", fields:
              [
                {label:"id", name:"id", widget:"string"},
                {label:"title", name:"title", widget:"string"},
                {label:"author", name:"author", widget:"string"},
                {label:"sector", name:"sector", widget:"string", required:false},
                {label:"tags", name:"tags", widget:"list", required:false},
                {label:"created", name:"created", widget:"datetime"},
                {label:"body", name:"body", widget:"text"}
              ]
            }
